version: "3"
services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    networks:
      - frontend
  redisinsignt:
    # 接続時は ifconfig en0 でホストPCのIPアドレスを取得する
    image: redislabs/redisinsight:latest
    container_name: redisinsignt
    depends_on:
      - redis
    ports:
      - "8001:8001"
    networks:
      - frontend
    volumes:
      - ./data/redisinsight:/db

networks:
  frontend:
